/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Breadcrumbs".
 */
export type Breadcrumbs = {
  slug: string;
  path: string;
  label: string;
  id?: string | null;
}[];
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'api-keys': ApiKeyAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {
    code: CodeBlock;
  };
  collections: {
    pages: Page;
    posts: Post;
    authors: Author;
    media: Media;
    avatar: Avatar;
    categories: Category;
    tags: Tag;
    'case-studies': CaseStudy;
    resources: Resource;
    'api-keys': ApiKey;
    redirects: Redirect;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    avatar: AvatarSelect<false> | AvatarSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    'api-keys': ApiKeysSelect<false> | ApiKeysSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('de' | 'en') | ('de' | 'en')[];
  globals: {
    header: Header;
    footer: Footer;
    labels: Labels;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    labels: LabelsSelect<false> | LabelsSelect<true>;
  };
  locale: 'de' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: ApiKey | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface ApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  code: string;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  isRootPage?: boolean | null;
  slug: string;
  parent?: (string | null) | Page;
  path: string;
  breadcrumbs: Breadcrumbs;
  title: string;
  /**
   * Flagged by migration script — page content imported from Elementor JSON and needs manual block reconstruction
   */
  needsRebuild?: boolean | null;
  hero: HeroSection;
  /**
   * When enabled, hides header, footer, hero section, and page title — the block content becomes the full page.
   */
  hidePageShell?: boolean | null;
  /**
   * Allow public access to this page (useful for login pages)
   */
  public?: boolean | null;
  sections?:
    | {
        title?: string | null;
        subTitle?: string | null;
        highlightBackground?: boolean | null;
        blocks?:
          | (
              | BrandsBlock
              | AboutBlock
              | TransparencyBlock
              | AdvantagesOfHeroBlock
              | ServicesBlock
              | Services2Block
              | WhyChooseBlock
              | TestimonialsBlock
              | DynamicWordPressBlock
              | PortfolioCarouselBlock
              | AgencyHeroBrandsBlock
              | CtaBlock
              | RichTextBlock
              | BlogPostsBlock
              | AuthorsBlock
              | CaseStudyCarouselBlock
              | LoginBlock
              | OnlineBusinessBlock
              | FeaturedCaseStudyBlock
              | CounselingBlock
              | PortfolioGridBlock
              | AboutSection1Block
              | AboutSection2Block
              | AboutSection3Block
              | AboutSection4Block
              | AboutSection5Block
              | WebTestimonialsBlock
              | WebSection2Block
              | WebSection6Block
              | SecretsBlock
              | OurSeoBlock
              | SeoServices2Block
              | SeoServices6Block
              | PricingSectionBlock
              | FaqSectionBlock
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  meta: SeoMetadata;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSection".
 */
export interface HeroSection {
  title: string;
  subtitle: string;
  backgroundImage?: (string | null) | Media;
  primaryCTA?: {
    label?: string | null;
    link?: (string | null) | Page;
  };
  secondaryCTA?: {
    label?: string | null;
    phone?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandsBlock".
 */
export interface BrandsBlock {
  heading: string;
  logos: {
    logo: string | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'brands';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock".
 */
export interface AboutBlock {
  image: string | Media;
  heading: string;
  description: string;
  primaryCta: {
    label: string;
    link?: (string | null) | Page;
    /**
     * Use this instead of link for external URLs
     */
    externalUrl?: string | null;
  };
  phoneCta: {
    label: string;
    phone: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'about';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TransparencyBlock".
 */
export interface TransparencyBlock {
  decorativeImage?: (string | null) | Media;
  features: {
    title: string;
    description: string;
    showCta?: boolean | null;
    ctaButton?: {
      label: string;
      link?: (string | null) | Page;
      externalUrl?: string | null;
    };
    phoneCta?: {
      label: string;
      phone: string;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'transparency';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AdvantagesOfHeroBlock".
 */
export interface AdvantagesOfHeroBlock {
  backgroundImage?: (string | null) | Media;
  heading: string;
  boldHeading: string;
  subtitle: string;
  description: string;
  ctaButton: {
    label: string;
    link: string;
  };
  testimonial: {
    quote: string;
    author: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'advantages-of-hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock".
 */
export interface ServicesBlock {
  heading: string;
  subtitle?: string | null;
  services: {
    icon: string | Media;
    title: string;
    description: string;
    ctaLabel: string;
    ctaLink?: (string | null) | Page;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'services';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Services2Block".
 */
export interface Services2Block {
  backgroundImage: string | Media;
  overlayImage?: (string | null) | Media;
  overlayText?: string | null;
  heading: string;
  headingHighlight: string;
  items: {
    number: string;
    title: string;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'services-2';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyChooseBlock".
 */
export interface WhyChooseBlock {
  heading: string;
  items: {
    number: string;
    title: string;
    description: string;
    isExpanded?: boolean | null;
    showCta?: boolean | null;
    ctaButton?: {
      label: string;
      link?: (string | null) | Page;
      externalUrl?: string | null;
    };
    phoneCta?: {
      label: string;
      phone: string;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'why-choose';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  heading: string;
  boldHeading?: string | null;
  ctaButton: {
    label: string;
    link?: (string | null) | Page;
    externalUrl?: string | null;
  };
  phoneCta: {
    label: string;
    phone: string;
  };
  testimonials: {
    rating?: number | null;
    quote: string;
    author: string;
    role?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DynamicWordPressBlock".
 */
export interface DynamicWordPressBlock {
  backgroundImage?: (string | null) | Media;
  heading: string;
  boldHeading: string;
  description: string;
  ctaButton: {
    label: string;
    link?: (string | null) | Page;
    /**
     * Use this instead of link for external URLs
     */
    externalUrl?: string | null;
  };
  phoneCta: {
    label: string;
    phone: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'dynamic-wordpress';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioCarouselBlock".
 */
export interface PortfolioCarouselBlock {
  heading: string;
  boldHeading?: string | null;
  description: string;
  subDescription?: string | null;
  ctaButton: {
    label: string;
    link?: (string | null) | Page;
    /**
     * Use this instead of link for external URLs
     */
    externalUrl?: string | null;
  };
  phoneCta: {
    label: string;
    phone: string;
  };
  projects: {
    image: string | Media;
    title: string;
    description?: string | null;
    link?: (string | null) | Page;
    id?: string | null;
  }[];
  viewAllLink?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'portfolio-carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AgencyHeroBrandsBlock".
 */
export interface AgencyHeroBrandsBlock {
  eyebrow: string;
  heading: string;
  logos: {
    logo: string | Media;
    width?: number | null;
    height?: number | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'agency-hero-brands';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  image: string | Media;
  heading: string;
  subtext?: string | null;
  ctaButton: {
    label: string;
    link?: (string | null) | Page;
    /**
     * Use this instead of link for external URLs (e.g., https://example.com)
     */
    externalUrl?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'rich-text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogPostsBlock".
 */
export interface BlogPostsBlock {
  heading: string;
  /**
   * Select blog posts to display
   */
  posts: (string | Post)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'blog-posts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  slug: string;
  parent: string | Page;
  path: string;
  breadcrumbs: Breadcrumbs;
  authors: (string | Author)[];
  categories?: (string | Category)[] | null;
  tags?: (string | Tag)[] | null;
  /**
   * Estimated reading time in minutes
   */
  readingTime?: number | null;
  title: string;
  excerpt: string;
  image: string | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta: SeoMetadata;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: string;
  slug: string;
  parent: string | Page;
  path: string;
  breadcrumbs: Breadcrumbs;
  name: string;
  profession: string;
  photo: string | Media;
  excerpt: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta: SeoMetadata;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SeoMetadata".
 */
export interface SeoMetadata {
  title?: string | null;
  description?: string | null;
  /**
   * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
   */
  image?: (string | null) | Media;
  /**
   * Primary keyword for SEO optimization
   */
  focusKeyword?: string | null;
  /**
   * If checked, a noindex meta tag will be added to the page and it will be excluded from the sitemap.
   */
  noIndex?: boolean | null;
  alternatePaths: {
    hreflang: string;
    path: string;
    id?: string | null;
  }[];
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AuthorsBlock".
 */
export interface AuthorsBlock {
  authors: (string | Author)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'authors';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyCarouselBlock".
 */
export interface CaseStudyCarouselBlock {
  /**
   * Main heading above the carousel
   */
  sectionHeading: string;
  /**
   * Subheading below main heading
   */
  sectionSubheading?: string | null;
  /**
   * Shared background image for every slide
   */
  backgroundImage?: (string | null) | Media;
  caseStudies: {
    eyebrow?: string | null;
    heading: string;
    description: string;
    ctaButton: {
      label: string;
      link: string;
    };
    testimonial: {
      quote: string;
      author: string;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'case-study-carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LoginBlock".
 */
export interface LoginBlock {
  backgroundImage?: (string | null) | Media;
  logo?: (string | null) | Media;
  title?: string | null;
  titleHighlight?: string | null;
  emailPlaceholder?: string | null;
  passwordPlaceholder?: string | null;
  forgotPasswordLabel?: string | null;
  forgotPasswordLink?: (string | null) | Page;
  buttonLabel?: string | null;
  registerLabel?: string | null;
  registerIcon?: (string | null) | Media;
  registerLink?: (string | null) | Page;
  id?: string | null;
  blockName?: string | null;
  blockType: 'login';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OnlineBusinessBlock".
 */
export interface OnlineBusinessBlock {
  heading: string;
  /**
   * Bold portion of the heading
   */
  boldHeading?: string | null;
  items: {
    number: string;
    title: string;
    description: string;
    isExpanded?: boolean | null;
    showCta?: boolean | null;
    ctaButton?: {
      label: string;
      link?: (string | null) | Page;
      externalUrl?: string | null;
    };
    phoneCta?: {
      label: string;
      phone: string;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'online-business';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCaseStudyBlock".
 */
export interface FeaturedCaseStudyBlock {
  /**
   * Category label above the heading (e.g. "Counseling Practice")
   */
  eyebrow?: string | null;
  /**
   * Main case study title
   */
  heading: string;
  /**
   * Short description of the case study
   */
  description?: string | null;
  ctaButton: {
    label: string;
    link: string;
  };
  /**
   * Full-width background image
   */
  backgroundImage?: (string | null) | Media;
  /**
   * Featured image displayed on the left side
   */
  featuredImage?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featured-case-study';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CounselingBlock".
 */
export interface CounselingBlock {
  /**
   * Heading text like "Counseling Practice"
   */
  heading: string;
  /**
   * Subheading like "Practice" on the next line in bold
   */
  subheading: string;
  /**
   * Full-width background image on the left side
   */
  backgroundImage?: (string | null) | Media;
  testimonialCard: {
    text: string;
    author: string;
  };
  caseStudy: {
    label: string;
    description: string;
    ctaButton: {
      label: string;
      link: string;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'counseling';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioGridBlock".
 */
export interface PortfolioGridBlock {
  heading: string;
  categories?:
    | {
        label: string;
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  items: {
    title: string;
    /**
     * Must match one of the category labels above (e.g. "E-commerce")
     */
    category?: string | null;
    description?: string | null;
    image: string | Media;
    metrics: {
      label: string;
      value: string;
      id?: string | null;
    }[];
    ctaLink?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'portfolio-grid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSection1Block".
 */
export interface AboutSection1Block {
  image: string | Media;
  heading: string;
  boldHeading?: string | null;
  description: string;
  /**
   * Bold highlighted text below description
   */
  highlightText?: string | null;
  primaryCta: {
    label: string;
    link?: (string | null) | Page;
    /**
     * Use this instead of link for external URLs
     */
    externalUrl?: string | null;
  };
  phoneCta: {
    label: string;
    phone: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'about-section-1';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSection2Block".
 */
export interface AboutSection2Block {
  heading: string;
  boldHeading?: string | null;
  teamMembers: {
    name: string;
    image: string | Media;
    role: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'about-section-2';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSection3Block".
 */
export interface AboutSection3Block {
  heading: string;
  boldHeading?: string | null;
  brandLogos: {
    logo: string | Media;
    id?: string | null;
  }[];
  banners: {
    heading: string;
    boldHeading?: string | null;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'about-section-3';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSection4Block".
 */
export interface AboutSection4Block {
  heading: string;
  boldHeading?: string | null;
  description: string;
  rating?: number | null;
  testimonial: {
    quote: string;
    author: string;
    role?: string | null;
  };
  primaryCta: {
    label: string;
    link?: (string | null) | Page;
    /**
     * Use this instead of link for external URLs
     */
    externalUrl?: string | null;
  };
  phoneCta: {
    label: string;
    phone: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'about-section-4';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSection5Block".
 */
export interface AboutSection5Block {
  backgroundImage: string | Media;
  heading: string;
  boldHeading?: string | null;
  description: string;
  primaryCta: {
    label: string;
    link?: (string | null) | Page;
    /**
     * Use this instead of link for external URLs
     */
    externalUrl?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'about-section-5';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WebTestimonialsBlock".
 */
export interface WebTestimonialsBlock {
  testimonials: {
    rating?: number | null;
    quote: string;
    author: string;
    role?: string | null;
    authorImage?: (string | null) | Media;
    id?: string | null;
  }[];
  scrollText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'web-testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WebSection2Block".
 */
export interface WebSection2Block {
  heading: string;
  subheading?: string | null;
  logos: {
    logo: string | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'web-section-2';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WebSection6Block".
 */
export interface WebSection6Block {
  heading: string;
  highlightedText?: string | null;
  items: {
    icon?: (string | null) | Media;
    text: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'web-section-6';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SecretsBlock".
 */
export interface SecretsBlock {
  heading: string;
  headingHighlight: string;
  subheading?: string | null;
  items: {
    number: string;
    title: string;
    description: string;
    isExpanded?: boolean | null;
    showCta?: boolean | null;
    ctaButton?: {
      label: string;
      link?: (string | null) | Page;
      externalUrl?: string | null;
    };
    phoneCta?: {
      label: string;
      phone: string;
    };
    id?: string | null;
  }[];
  backgroundImage?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'secrets';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OurSeoBlock".
 */
export interface OurSeoBlock {
  heading: string;
  headingHighlight: string;
  items: {
    number: string;
    title: string;
    description: string;
    showCta?: boolean | null;
    ctaButton?: {
      label: string;
      link?: (string | null) | Page;
      externalUrl?: string | null;
    };
    phoneCta?: {
      label: string;
      phone: string;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'our-seo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SeoServices2Block".
 */
export interface SeoServices2Block {
  heading: string;
  headingHighlight: string;
  subheading?: string | null;
  items: {
    icon?: (string | null) | Media;
    number: string;
    title: string;
    description: string;
    id?: string | null;
  }[];
  backgroundImage: string | Media;
  ctaButton?: {
    label?: string | null;
    link?: (string | null) | Page;
    externalUrl?: string | null;
  };
  phoneCta?: {
    label?: string | null;
    phone?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'seo-services-2';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SeoServices6Block".
 */
export interface SeoServices6Block {
  heading: string;
  headingHighlight: string;
  subheading?: string | null;
  items: {
    number: string;
    title: string;
    description: string;
    showCta?: boolean | null;
    ctaButton?: {
      label: string;
      link?: (string | null) | Page;
      externalUrl?: string | null;
    };
    phoneCta?: {
      label: string;
      phone: string;
    };
    isExpanded?: boolean | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'seo-services-6';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingSectionBlock".
 */
export interface PricingSectionBlock {
  heading: string;
  headingHighlight: string;
  subheading?: string | null;
  plans: {
    title: string;
    subtitle?: string | null;
    price: string;
    features: {
      text: string;
      id?: string | null;
    }[];
    ctaLabel: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing-section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqSectionBlock".
 */
export interface FaqSectionBlock {
  heading: string;
  items: {
    /**
     * Question number (e.g., 01, 02)
     */
    number: string;
    question: string;
    answer: string;
    isExpanded?: boolean | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq-section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avatar".
 */
export interface Avatar {
  id: string;
  image: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: string;
  slug: string;
  parent: string | Page;
  path: string;
  breadcrumbs: Breadcrumbs;
  title: string;
  client: string;
  industry:
    | 'app'
    | 'cannabis-cbd'
    | 'corporate'
    | 'e-commerce'
    | 'health-care'
    | 'manufacturing'
    | 'real-estate'
    | 'roofing';
  publishedDate?: string | null;
  featuredImage: string | Media;
  aboutText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  challengeText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  solutionText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  resultsText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta: SeoMetadata;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: string;
  slug: string;
  parent: string | Page;
  path: string;
  breadcrumbs: Breadcrumbs;
  title: string;
  url: string;
  category?:
    | ('ecommerce-platforms' | 'email-marketing-apps' | 'online-marketing-apps' | 'stock-assets' | 'website-apps')
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  icon?: (string | null) | Media;
  meta: SeoMetadata;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys".
 */
export interface ApiKey {
  id: string;
  type: 'website' | 'agent';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  sourcePath: string;
  destinationPath: string;
  type: 'permanent' | 'temporary';
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  roles: ('editor' | 'admin' | 'developer')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'authors';
        value: string | Author;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'avatar';
        value: string | Avatar;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: string | CaseStudy;
      } | null)
    | ({
        relationTo: 'resources';
        value: string | Resource;
      } | null)
    | ({
        relationTo: 'api-keys';
        value: string | ApiKey;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'api-keys';
        value: string | ApiKey;
      }
    | {
        relationTo: 'users';
        value: string | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'api-keys';
        value: string | ApiKey;
      }
    | {
        relationTo: 'users';
        value: string | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  isRootPage?: T;
  slug?: T;
  parent?: T;
  path?: T;
  breadcrumbs?: T | BreadcrumbsSelect<T>;
  title?: T;
  needsRebuild?: T;
  hero?: T | HeroSectionSelect<T>;
  hidePageShell?: T;
  public?: T;
  sections?:
    | T
    | {
        title?: T;
        subTitle?: T;
        highlightBackground?: T;
        blocks?:
          | T
          | {
              brands?: T | BrandsBlockSelect<T>;
              about?: T | AboutBlockSelect<T>;
              transparency?: T | TransparencyBlockSelect<T>;
              'advantages-of-hero'?: T | AdvantagesOfHeroBlockSelect<T>;
              services?: T | ServicesBlockSelect<T>;
              'services-2'?: T | Services2BlockSelect<T>;
              'why-choose'?: T | WhyChooseBlockSelect<T>;
              testimonials?: T | TestimonialsBlockSelect<T>;
              'dynamic-wordpress'?: T | DynamicWordPressBlockSelect<T>;
              'portfolio-carousel'?: T | PortfolioCarouselBlockSelect<T>;
              'agency-hero-brands'?: T | AgencyHeroBrandsBlockSelect<T>;
              cta?: T | CtaBlockSelect<T>;
              'rich-text'?: T | RichTextBlockSelect<T>;
              'blog-posts'?: T | BlogPostsBlockSelect<T>;
              authors?: T | AuthorsBlockSelect<T>;
              'case-study-carousel'?: T | CaseStudyCarouselBlockSelect<T>;
              login?: T | LoginBlockSelect<T>;
              'online-business'?: T | OnlineBusinessBlockSelect<T>;
              'featured-case-study'?: T | FeaturedCaseStudyBlockSelect<T>;
              counseling?: T | CounselingBlockSelect<T>;
              'portfolio-grid'?: T | PortfolioGridBlockSelect<T>;
              'about-section-1'?: T | AboutSection1BlockSelect<T>;
              'about-section-2'?: T | AboutSection2BlockSelect<T>;
              'about-section-3'?: T | AboutSection3BlockSelect<T>;
              'about-section-4'?: T | AboutSection4BlockSelect<T>;
              'about-section-5'?: T | AboutSection5BlockSelect<T>;
              'web-testimonials'?: T | WebTestimonialsBlockSelect<T>;
              'web-section-2'?: T | WebSection2BlockSelect<T>;
              'web-section-6'?: T | WebSection6BlockSelect<T>;
              secrets?: T | SecretsBlockSelect<T>;
              'our-seo'?: T | OurSeoBlockSelect<T>;
              'seo-services-2'?: T | SeoServices2BlockSelect<T>;
              'seo-services-6'?: T | SeoServices6BlockSelect<T>;
              'pricing-section'?: T | PricingSectionBlockSelect<T>;
              'faq-section'?: T | FaqSectionBlockSelect<T>;
            };
        id?: T;
      };
  meta?: T | SeoMetadataSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Breadcrumbs_select".
 */
export interface BreadcrumbsSelect<T extends boolean = true> {
  slug?: T;
  path?: T;
  label?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSection_select".
 */
export interface HeroSectionSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  backgroundImage?: T;
  primaryCTA?:
    | T
    | {
        label?: T;
        link?: T;
      };
  secondaryCTA?:
    | T
    | {
        label?: T;
        phone?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandsBlock_select".
 */
export interface BrandsBlockSelect<T extends boolean = true> {
  heading?: T;
  logos?:
    | T
    | {
        logo?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlock_select".
 */
export interface AboutBlockSelect<T extends boolean = true> {
  image?: T;
  heading?: T;
  description?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        link?: T;
        externalUrl?: T;
      };
  phoneCta?:
    | T
    | {
        label?: T;
        phone?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TransparencyBlock_select".
 */
export interface TransparencyBlockSelect<T extends boolean = true> {
  decorativeImage?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        showCta?: T;
        ctaButton?:
          | T
          | {
              label?: T;
              link?: T;
              externalUrl?: T;
            };
        phoneCta?:
          | T
          | {
              label?: T;
              phone?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AdvantagesOfHeroBlock_select".
 */
export interface AdvantagesOfHeroBlockSelect<T extends boolean = true> {
  backgroundImage?: T;
  heading?: T;
  boldHeading?: T;
  subtitle?: T;
  description?: T;
  ctaButton?:
    | T
    | {
        label?: T;
        link?: T;
      };
  testimonial?:
    | T
    | {
        quote?: T;
        author?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock_select".
 */
export interface ServicesBlockSelect<T extends boolean = true> {
  heading?: T;
  subtitle?: T;
  services?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        ctaLabel?: T;
        ctaLink?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Services2Block_select".
 */
export interface Services2BlockSelect<T extends boolean = true> {
  backgroundImage?: T;
  overlayImage?: T;
  overlayText?: T;
  heading?: T;
  headingHighlight?: T;
  items?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyChooseBlock_select".
 */
export interface WhyChooseBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        isExpanded?: T;
        showCta?: T;
        ctaButton?:
          | T
          | {
              label?: T;
              link?: T;
              externalUrl?: T;
            };
        phoneCta?:
          | T
          | {
              label?: T;
              phone?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  boldHeading?: T;
  ctaButton?:
    | T
    | {
        label?: T;
        link?: T;
        externalUrl?: T;
      };
  phoneCta?:
    | T
    | {
        label?: T;
        phone?: T;
      };
  testimonials?:
    | T
    | {
        rating?: T;
        quote?: T;
        author?: T;
        role?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DynamicWordPressBlock_select".
 */
export interface DynamicWordPressBlockSelect<T extends boolean = true> {
  backgroundImage?: T;
  heading?: T;
  boldHeading?: T;
  description?: T;
  ctaButton?:
    | T
    | {
        label?: T;
        link?: T;
        externalUrl?: T;
      };
  phoneCta?:
    | T
    | {
        label?: T;
        phone?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioCarouselBlock_select".
 */
export interface PortfolioCarouselBlockSelect<T extends boolean = true> {
  heading?: T;
  boldHeading?: T;
  description?: T;
  subDescription?: T;
  ctaButton?:
    | T
    | {
        label?: T;
        link?: T;
        externalUrl?: T;
      };
  phoneCta?:
    | T
    | {
        label?: T;
        phone?: T;
      };
  projects?:
    | T
    | {
        image?: T;
        title?: T;
        description?: T;
        link?: T;
        id?: T;
      };
  viewAllLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AgencyHeroBrandsBlock_select".
 */
export interface AgencyHeroBrandsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  logos?:
    | T
    | {
        logo?: T;
        width?: T;
        height?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  image?: T;
  heading?: T;
  subtext?: T;
  ctaButton?:
    | T
    | {
        label?: T;
        link?: T;
        externalUrl?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  text?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlogPostsBlock_select".
 */
export interface BlogPostsBlockSelect<T extends boolean = true> {
  heading?: T;
  posts?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AuthorsBlock_select".
 */
export interface AuthorsBlockSelect<T extends boolean = true> {
  authors?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyCarouselBlock_select".
 */
export interface CaseStudyCarouselBlockSelect<T extends boolean = true> {
  sectionHeading?: T;
  sectionSubheading?: T;
  backgroundImage?: T;
  caseStudies?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        ctaButton?:
          | T
          | {
              label?: T;
              link?: T;
            };
        testimonial?:
          | T
          | {
              quote?: T;
              author?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LoginBlock_select".
 */
export interface LoginBlockSelect<T extends boolean = true> {
  backgroundImage?: T;
  logo?: T;
  title?: T;
  titleHighlight?: T;
  emailPlaceholder?: T;
  passwordPlaceholder?: T;
  forgotPasswordLabel?: T;
  forgotPasswordLink?: T;
  buttonLabel?: T;
  registerLabel?: T;
  registerIcon?: T;
  registerLink?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OnlineBusinessBlock_select".
 */
export interface OnlineBusinessBlockSelect<T extends boolean = true> {
  heading?: T;
  boldHeading?: T;
  items?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        isExpanded?: T;
        showCta?: T;
        ctaButton?:
          | T
          | {
              label?: T;
              link?: T;
              externalUrl?: T;
            };
        phoneCta?:
          | T
          | {
              label?: T;
              phone?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCaseStudyBlock_select".
 */
export interface FeaturedCaseStudyBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  ctaButton?:
    | T
    | {
        label?: T;
        link?: T;
      };
  backgroundImage?: T;
  featuredImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CounselingBlock_select".
 */
export interface CounselingBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  backgroundImage?: T;
  testimonialCard?:
    | T
    | {
        text?: T;
        author?: T;
      };
  caseStudy?:
    | T
    | {
        label?: T;
        description?: T;
        ctaButton?:
          | T
          | {
              label?: T;
              link?: T;
            };
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortfolioGridBlock_select".
 */
export interface PortfolioGridBlockSelect<T extends boolean = true> {
  heading?: T;
  categories?:
    | T
    | {
        label?: T;
        isActive?: T;
        id?: T;
      };
  items?:
    | T
    | {
        title?: T;
        category?: T;
        description?: T;
        image?: T;
        metrics?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        ctaLink?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSection1Block_select".
 */
export interface AboutSection1BlockSelect<T extends boolean = true> {
  image?: T;
  heading?: T;
  boldHeading?: T;
  description?: T;
  highlightText?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        link?: T;
        externalUrl?: T;
      };
  phoneCta?:
    | T
    | {
        label?: T;
        phone?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSection2Block_select".
 */
export interface AboutSection2BlockSelect<T extends boolean = true> {
  heading?: T;
  boldHeading?: T;
  teamMembers?:
    | T
    | {
        name?: T;
        image?: T;
        role?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSection3Block_select".
 */
export interface AboutSection3BlockSelect<T extends boolean = true> {
  heading?: T;
  boldHeading?: T;
  brandLogos?:
    | T
    | {
        logo?: T;
        id?: T;
      };
  banners?:
    | T
    | {
        heading?: T;
        boldHeading?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSection4Block_select".
 */
export interface AboutSection4BlockSelect<T extends boolean = true> {
  heading?: T;
  boldHeading?: T;
  description?: T;
  rating?: T;
  testimonial?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
      };
  primaryCta?:
    | T
    | {
        label?: T;
        link?: T;
        externalUrl?: T;
      };
  phoneCta?:
    | T
    | {
        label?: T;
        phone?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSection5Block_select".
 */
export interface AboutSection5BlockSelect<T extends boolean = true> {
  backgroundImage?: T;
  heading?: T;
  boldHeading?: T;
  description?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        link?: T;
        externalUrl?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WebTestimonialsBlock_select".
 */
export interface WebTestimonialsBlockSelect<T extends boolean = true> {
  testimonials?:
    | T
    | {
        rating?: T;
        quote?: T;
        author?: T;
        role?: T;
        authorImage?: T;
        id?: T;
      };
  scrollText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WebSection2Block_select".
 */
export interface WebSection2BlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  logos?:
    | T
    | {
        logo?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WebSection6Block_select".
 */
export interface WebSection6BlockSelect<T extends boolean = true> {
  heading?: T;
  highlightedText?: T;
  items?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SecretsBlock_select".
 */
export interface SecretsBlockSelect<T extends boolean = true> {
  heading?: T;
  headingHighlight?: T;
  subheading?: T;
  items?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        isExpanded?: T;
        showCta?: T;
        ctaButton?:
          | T
          | {
              label?: T;
              link?: T;
              externalUrl?: T;
            };
        phoneCta?:
          | T
          | {
              label?: T;
              phone?: T;
            };
        id?: T;
      };
  backgroundImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OurSeoBlock_select".
 */
export interface OurSeoBlockSelect<T extends boolean = true> {
  heading?: T;
  headingHighlight?: T;
  items?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        showCta?: T;
        ctaButton?:
          | T
          | {
              label?: T;
              link?: T;
              externalUrl?: T;
            };
        phoneCta?:
          | T
          | {
              label?: T;
              phone?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SeoServices2Block_select".
 */
export interface SeoServices2BlockSelect<T extends boolean = true> {
  heading?: T;
  headingHighlight?: T;
  subheading?: T;
  items?:
    | T
    | {
        icon?: T;
        number?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  backgroundImage?: T;
  ctaButton?:
    | T
    | {
        label?: T;
        link?: T;
        externalUrl?: T;
      };
  phoneCta?:
    | T
    | {
        label?: T;
        phone?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SeoServices6Block_select".
 */
export interface SeoServices6BlockSelect<T extends boolean = true> {
  heading?: T;
  headingHighlight?: T;
  subheading?: T;
  items?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        showCta?: T;
        ctaButton?:
          | T
          | {
              label?: T;
              link?: T;
              externalUrl?: T;
            };
        phoneCta?:
          | T
          | {
              label?: T;
              phone?: T;
            };
        isExpanded?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingSectionBlock_select".
 */
export interface PricingSectionBlockSelect<T extends boolean = true> {
  heading?: T;
  headingHighlight?: T;
  subheading?: T;
  plans?:
    | T
    | {
        title?: T;
        subtitle?: T;
        price?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaLabel?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqSectionBlock_select".
 */
export interface FaqSectionBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        number?: T;
        question?: T;
        answer?: T;
        isExpanded?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SeoMetadata_select".
 */
export interface SeoMetadataSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  focusKeyword?: T;
  noIndex?: T;
  alternatePaths?:
    | T
    | {
        hreflang?: T;
        path?: T;
        id?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  slug?: T;
  parent?: T;
  path?: T;
  breadcrumbs?: T | BreadcrumbsSelect<T>;
  authors?: T;
  categories?: T;
  tags?: T;
  readingTime?: T;
  title?: T;
  excerpt?: T;
  image?: T;
  content?: T;
  meta?: T | SeoMetadataSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  slug?: T;
  parent?: T;
  path?: T;
  breadcrumbs?: T | BreadcrumbsSelect<T>;
  name?: T;
  profession?: T;
  photo?: T;
  excerpt?: T;
  description?: T;
  meta?: T | SeoMetadataSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avatar_select".
 */
export interface AvatarSelect<T extends boolean = true> {
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  slug?: T;
  parent?: T;
  path?: T;
  breadcrumbs?: T | BreadcrumbsSelect<T>;
  title?: T;
  client?: T;
  industry?: T;
  publishedDate?: T;
  featuredImage?: T;
  aboutText?: T;
  challengeText?: T;
  solutionText?: T;
  resultsText?: T;
  meta?: T | SeoMetadataSelect<T>;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  slug?: T;
  parent?: T;
  path?: T;
  breadcrumbs?: T | BreadcrumbsSelect<T>;
  title?: T;
  url?: T;
  category?: T;
  description?: T;
  icon?: T;
  meta?: T | SeoMetadataSelect<T>;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-keys_select".
 */
export interface ApiKeysSelect<T extends boolean = true> {
  type?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  sourcePath?: T;
  destinationPath?: T;
  type?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo: string | Media;
  links?:
    | {
        page: string | Page;
        label: string;
        /**
         * Enable dropdown menu for this link
         */
        enableDropdown?: boolean | null;
        /**
         * Configure dropdown menu for this link
         */
        dropdown?: {
          services?:
            | {
                title: string;
                link?: (string | null) | Page;
                /**
                 * Show in orange color (first item style)
                 */
                highlighted?: boolean | null;
                id?: string | null;
              }[]
            | null;
          testimonial: {
            quote: string;
            authorName: string;
            authorTitle?: string | null;
            authorImage?: (string | null) | Media;
          };
          /**
           * Background image for the right side of dropdown
           */
          backgroundImage?: (string | null) | Media;
        };
        id?: string | null;
      }[]
    | null;
  phone?: string | null;
  clientLoginLink?: string | null;
  cta?: {
    label?: string | null;
    link?: (string | null) | Page;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  logoText: string;
  description: string;
  socialLinks?:
    | {
        platform: 'facebook' | 'linkedin' | 'behance' | 'instagram' | 'twitter' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  links?:
    | {
        page: string | Page;
        label: string;
        id?: string | null;
      }[]
    | null;
  talkTitle: string;
  phone?: string | null;
  locationText?: string | null;
  address?: string | null;
  ctaTitle?: string | null;
  ctaButtonLabel?: string | null;
  ctaButtonUrl?: string | null;
  /**
   * Select a post to display in the footer right column. If none selected, the latest post will be displayed.
   */
  featuredPost?: (string | null) | Post;
  transparencyText?: string | null;
  copyright?: string | null;
  bottomLinks?:
    | {
        page: string | Page;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labels".
 */
export interface Labels {
  id: string;
  global: {
    'show-more': string;
    'learn-more': string;
    'open-menu': string;
    'close-menu': string;
  };
  posts: {
    'written-by': string;
    'last-updated-at': string;
  };
  'not-found-page': {
    title: string;
    description: string;
    'home-page-button': string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  links?:
    | T
    | {
        page?: T;
        label?: T;
        enableDropdown?: T;
        dropdown?:
          | T
          | {
              services?:
                | T
                | {
                    title?: T;
                    link?: T;
                    highlighted?: T;
                    id?: T;
                  };
              testimonial?:
                | T
                | {
                    quote?: T;
                    authorName?: T;
                    authorTitle?: T;
                    authorImage?: T;
                  };
              backgroundImage?: T;
            };
        id?: T;
      };
  phone?: T;
  clientLoginLink?: T;
  cta?:
    | T
    | {
        label?: T;
        link?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logoText?: T;
  description?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  links?:
    | T
    | {
        page?: T;
        label?: T;
        id?: T;
      };
  talkTitle?: T;
  phone?: T;
  locationText?: T;
  address?: T;
  ctaTitle?: T;
  ctaButtonLabel?: T;
  ctaButtonUrl?: T;
  featuredPost?: T;
  transparencyText?: T;
  copyright?: T;
  bottomLinks?:
    | T
    | {
        page?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "labels_select".
 */
export interface LabelsSelect<T extends boolean = true> {
  global?:
    | T
    | {
        'show-more'?: T;
        'learn-more'?: T;
        'open-menu'?: T;
        'close-menu'?: T;
      };
  posts?:
    | T
    | {
        'written-by'?: T;
        'last-updated-at'?: T;
      };
  'not-found-page'?:
    | T
    | {
        title?: T;
        description?: T;
        'home-page-button'?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}